name: React Quickstart CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Yarn install with caching
        uses: bahmutov/npm-install@v1.6.0

      - name: Run lint checks
        run: yarn lint

      - name: Run build
        run: yarn build

      - name: Run tests with coverage reports
        run: yarn test:coverage

      - name: Upload coverage report to codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
